[project]
site_name = "changelog-slugs documentation"
site_description = "Changelog-aware heading slugs for Python-Markdown’s toc extension"
site_author = "Johann Philipp Gorzny"
site_url = "https://jo-phil.github.io/changelog-slugs/"
repo_url = "https://github.com/jo-phil/changelog-slugs"

nav = [
    {"Home" = "index.md"},
    {"API reference" = "api.md"},
    {"Changelog" = "changelog.md"},
    {"License" = "license.md"},
]

[project.theme]
features = [
    "content.code.copy",
    "content.tabs.link",
    "content.tooltips",
    "navigation.top",
    "search.highlight",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[[project.extra.social]]
icon = "simple/github"
link = "https://github.com/jo-phil/changelog-slugs"
[[project.extra.social]]
icon = "simple/pypi"
link = "https://pypi.org/project/changelog-slugs/"

[project.markdown_extensions.toc]
permalink = true
slugify.object = "changelog_slugs.Slugifier"

[project.markdown_extensions.pymdownx.snippets]
base_path = ["."]

[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
slugify = { object = "pymdownx.slugs.slugify", kwds = { case = "lower" } }

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
members_order = "source"
separate_signature = true
show_root_heading = true
show_root_toc_entry = false
show_source = false
